import type { FareItemKind, InteractionContext } from './sceneTypes';

export const CONTEXT_COPY: Record<InteractionContext, string> = {
  walking: 'Choose Bus 50 or follow Exit B for the LRT',
  'bus-stop': 'Wait inside bus stop 65321',
  stairs: 'Enter Kadaloor LRT station',
  'bus-arriving': 'Service 50 is approaching',
  boarding: 'Walk through the open front door',
  'choose-item': 'Choose a fare item from your bag',
  'item-selected': 'Stand beside the reader and tap your card',
  reader: 'Walk to the SimplyGo reader',
  'wrong-item': 'Choose the travel card instead',
  'driver-warning': 'Driver: “Tap in before moving down the bus.”',
  tapping: 'Tapping card…',
  'fare-success': 'ENTRY OK — move into the bus',
  standing: 'Hold on while the bus departs',
  seated: 'Seated safely while the bus departs',
  'bus-moving': 'Travelling to Punggol',
  aisle: 'Choose a highlighted seat or remain standing',
  'bus-stop-open': 'Intermediate stop — remain aboard for Punggol',
  'tap-out': 'Doors open — tap either exit reader',
  'choose-exit-item': 'Choose the travel card from your bag',
  'exit-item-selected': 'Stand beside an exit reader and tap',
  'tap-out-warning': 'Tap out before leaving the bus',
  'last-stop-reminder': 'Punggol Interchange — tap out, then alight',
  'exit-ok': 'EXIT OK — walk through the rear doors',
  alighting: 'Alighting at Punggol Interchange',
  'wrong-stop': 'Wrong stop — returning to Kadaloor',
  'lrt-gates': 'Stand beside a green TAP reader and tap in',
  'lrt-tapping': 'Tapping into Kadaloor LRT…',
  'lrt-gates-open': 'ENTRY OK — walk through the open lane',
  'lrt-stairs': 'Follow the stairs to the LRT platform',
  'lrt-platform': 'Choose the train towards Punggol',
  'lrt-arriving': 'Punggol LRT is approaching',
  'lrt-boarding': 'Doors open — walk aboard',
  'lrt-riding': 'Ride to Punggol',
  'nel-transfer': 'Check the platform signs and wait for the train towards HarbourFront',
  'nel-wrong-direction': 'This train goes to Punggol Coast. Take the HarbourFront-bound train for Little India.',
  'nel-arriving': 'North East Line train is approaching',
  'nel-boarding': 'Doors open — walk aboard',
  'nel-riding': 'Ride to Little India',
  'punggol-transfer': 'Follow signs to the North East Line',
  'punggol-gates': 'Stand beside a green TAP reader and tap in',
  'punggol-tapping': 'Tapping into the North East Line…',
  'punggol-gates-open': 'ENTRY OK — walk through the open lane',
  'punggol-escalator': 'Walk to the down escalator',
  'punggol-escalator-riding': 'Descending to the North East Line…',
  'little-india-alight': 'Follow signs to the Downtown Line',
  'little-india-transfer': 'Continue to the Downtown Line',
  'dtl-transfer': 'Choose the platform towards Expo',
  'dtl-wrong-direction': 'Wrong direction — choose Expo',
  'dtl-arriving': 'Downtown Line train is approaching',
  'dtl-boarding': 'Doors open — walk aboard',
  'dtl-riding': 'Ride to Expo',
  'dtl-last-stop-reminder': 'Expo — walk through the open train door',
  'rail-wrong-stop': 'Wrong station — returning to the train',
  'out-of-time': 'Journey ended — travel time expired',
  'expo-alight': 'Follow the Exit D signs',
  'expo-fare-gates': 'Stand beside an OUT reader and tap out',
  'expo-tapping': 'Tapping out at Expo…',
  'expo-gates-open': 'EXIT OK — walk through the open lane',
  'expo-exit': 'Follow Exit D to Changi Business Park',
  'office-walk': 'Walk to The Signature main entrance',
  complete: 'Arrived at TCS · The Signature entrance',
};

export const BAG_ITEMS: Array<{ image: string; kind: FareItemKind; label: string }> = [
  { image: '/scenes/scene4/props/fare-item-umbrella.png', kind: 'umbrella', label: 'Umbrella' },
  { image: '/scenes/scene4/props/fare-item-travel-card.png', kind: 'travel-card', label: 'Travel card' },
  { image: '/scenes/scene4/props/fare-item-water-bottle.png', kind: 'water-bottle', label: 'Bottle' },
];
