import type { Mission } from '@/content/types';

export const missions: Mission[] = [
  {
    id: 'speak',
    title: 'Speak Like a Local',
    icon: '🗣️',
    category: 'lingo',
    subtitle: 'Get the hang of everyday Singlish.',
    order: 1,
    prerequisiteMissionIds: [],
    lessonIds: ['speak-l1', 'speak-l2', 'speak-l3', 'speak-l4', 'speak-l5'],
    completionXp: 120,
    badgeIdOnComplete: 'can-lah',
  },
  {
    id: 'eat',
    title: 'Eat Like a Local',
    icon: '🍜',
    category: 'food',
    subtitle: 'Hawker centres, kopi orders, and chope culture.',
    order: 2,
    prerequisiteMissionIds: ['speak'],
    lessonIds: ['eat-l1', 'eat-l2', 'eat-l3', 'eat-l4', 'eat-l5'],
    completionXp: 90,
    badgeIdOnComplete: 'makan-pro',
  },
  {
    id: 'move',
    title: 'Move Like a Local',
    icon: '🚇',
    category: 'gettingAround',
    subtitle: 'Master getting around Singapore.',
    order: 3,
    prerequisiteMissionIds: ['eat'],
    lessonIds: [
      'move-l1',
      'move-l2',
      'move-l3',
      'move-l4',
      'move-l5',
      'move-l6',
      'move-l7',
      'move-l8',
    ],
    completionXp: 120,
    badgeIdOnComplete: 'mrt-master',
  },
  {
    id: 'vibe',
    title: 'Vibe Like a Local',
    icon: '👀',
    category: 'socialVibes',
    subtitle: "Learn Singapore's unwritten social rules.",
    order: 4,
    prerequisiteMissionIds: ['move'],
    lessonIds: ['vibe-l1', 'vibe-l2', 'vibe-l3', 'vibe-l4', 'vibe-l5'],
    completionXp: 100,
    badgeIdOnComplete: 'read-the-room-badge',
  },
  {
    id: 'work',
    title: 'Work Like a Local',
    icon: '💼',
    category: 'workCulture',
    subtitle: 'Everyday habits for interns and young professionals.',
    order: 5,
    prerequisiteMissionIds: ['vibe'],
    lessonIds: ['work-l1', 'work-l2', 'work-l3', 'work-l4'],
    completionXp: 90,
  },
  {
    id: 'reallife',
    title: 'Real Life Mode',
    icon: '🏆',
    category: 'socialVibes',
    subtitle: 'The final challenge. Everything you’ve learned, remixed.',
    order: 6,
    prerequisiteMissionIds: ['work'],
    lessonIds: ['reallife-l1'],
    completionXp: 200,
    badgeIdOnComplete: 'sg-savvy-badge',
  },
];
