import type { Phrase } from '@/content/types';

export const phrases: Phrase[] = [
  // Speak Like a Local
  {
    id: 'can',
    word: 'Can',
    pronunciation: 'kahn',
    phonetic: '/kæn/',
    meaning: "Yes, sure, no problem — one of Singlish's most useful all-purpose words.",
    category: 'lingo',
    difficulty: 1,
    usedIn: ['Friends', 'Colleagues', 'Most everyday situations'],
    notUsedIn: ['Very formal written documents'],
    commonMistakes: [
      "Don't confuse it with just the English modal verb — here it also stands alone as a full 'yes'.",
    ],
    examples: [
      { text: '"Can you finish this by Friday?" — "Can!"' },
      { text: '"Table for two?" — "Can, this way please."' },
    ],
    missionId: 'speak',
  },
  {
    id: 'lah',
    word: 'Lah',
    pronunciation: 'lah',
    phonetic: '/lɑː/',
    meaning: 'A sentence-ending particle that softens a statement or adds emphasis and reassurance.',
    category: 'lingo',
    difficulty: 1,
    usedIn: ['Friends', 'Family', 'Casual chats'],
    notUsedIn: ['Formal presentations', 'Written business emails'],
    commonMistakes: [
      "Don't overuse it in formal writing — it's a spoken, casual marker.",
    ],
    examples: [
      { text: 'Wait for me lah, almost there!' },
      { text: 'Okay lah, no problem.' },
    ],
    missionId: 'speak',
  },
  {
    id: 'lor',
    word: 'Lor',
    pronunciation: 'law',
    phonetic: '/lɔː/',
    meaning: 'A particle signalling easy, resigned acceptance — like a shrug turned into a word.',
    category: 'lingo',
    difficulty: 2,
    usedIn: ['Friends', 'Casual chats'],
    notUsedIn: ['Formal settings'],
    examples: [
      { text: 'Okay lor, you decide.' },
      { text: 'If you say so lor.' },
    ],
    missionId: 'speak',
  },
  {
    id: 'shiok',
    word: 'Shiok',
    pronunciation: 'shee-ohk',
    phonetic: '/ʃɪɒk/',
    meaning: 'Really satisfying or great — used for good food, a cool breeze, or anything genuinely pleasing.',
    category: 'lingo',
    difficulty: 1,
    usedIn: ['Friends', 'Colleagues', 'Casual situations'],
    notUsedIn: ['Formal emails'],
    examples: [
      { text: 'This laksa is shiok!' },
      { text: 'Aircon on full blast — so shiok.' },
    ],
    missionId: 'speak',
  },
  {
    id: 'paiseh',
    word: 'Paiseh',
    pronunciation: 'pie-say',
    phonetic: '/paɪˈseɪ/',
    meaning: 'Embarrassed, shy, or a light apology for a small inconvenience.',
    category: 'lingo',
    difficulty: 2,
    usedIn: ['Friends', 'Colleagues', 'Casual apologies'],
    notUsedIn: ['Formal written apologies'],
    examples: [
      { text: 'Paiseh, I forgot to reply!' },
      { text: 'So paiseh, I stepped on your foot.' },
    ],
    missionId: 'speak',
  },
  {
    id: 'alamak',
    word: 'Alamak',
    pronunciation: 'ah-lah-mahk',
    phonetic: '/ˈɑːləˌmɑːk/',
    meaning: '"Oh no!" or "oh man!" — a burst of dismay, shock, or realising you\'ve messed up.',
    category: 'lingo',
    difficulty: 1,
    usedIn: ['Friends', 'Family', 'Any sudden bad news, big or small'],
    notUsedIn: ['Formal writing'],
    examples: [
      { text: "Alamak, I didn't know today was a public holiday!" },
      { text: 'Alamak, I left my wallet at home.' },
    ],
    missionId: 'speak',
  },
  {
    id: 'kiasu',
    word: 'Kiasu',
    pronunciation: 'kee-ah-soo',
    phonetic: '/ˈkiːɑːsuː/',
    meaning: "Literally 'afraid to lose out' — the urge to grab a good deal or be first, often said self-deprecatingly.",
    category: 'lingo',
    difficulty: 2,
    usedIn: ['Friends', 'Everyday self-deprecating jokes'],
    notUsedIn: ['As a serious insult — it usually lands as light teasing'],
    examples: [
      { text: 'He queued 2 hours for a free sample — so kiasu.' },
    ],
    missionId: 'speak',
  },
  {
    id: 'blur',
    word: 'Blur',
    pronunciation: 'blur',
    phonetic: '/blɜː/',
    meaning: 'Confused, out of the loop, or a bit dazed — usually said affectionately, not as an insult.',
    category: 'lingo',
    difficulty: 1,
    usedIn: ['Friends', 'Colleagues', 'Light teasing'],
    notUsedIn: ['As a serious put-down'],
    examples: [
      { text: 'Wah, you very blur today ah, meeting already started.' },
    ],
    missionId: 'speak',
  },
  {
    id: 'steady',
    word: 'Steady',
    pronunciation: 'ste-dee',
    phonetic: '/ˈstɛdi/',
    meaning: "Solid, reliable, all-sorted — a flexible word of approval. Can also mean 'in a relationship' (\"we going steady\").",
    category: 'lingo',
    difficulty: 1,
    usedIn: ['Friends', 'Confirming a plan', 'Praising someone competent'],
    examples: [
      { text: 'Steady, see you at 8!' },
      { text: 'He handled that client meeting steady one.' },
    ],
    missionId: 'speak',
  },
  {
    id: 'leh',
    word: 'Leh',
    pronunciation: 'leh',
    phonetic: '/lɛ/',
    meaning: 'A softer particle than "lah" — floats a suggestion or gently pushes back, without any real pressure.',
    category: 'lingo',
    difficulty: 2,
    usedIn: ['Friends', 'Colleagues', 'Suggesting an alternative'],
    notUsedIn: ['Formal writing'],
    examples: [
      { text: 'Movie got later showing leh, wanna catch that instead?' },
      { text: "Actually quite far leh, sure you want to walk?" },
    ],
    missionId: 'speak',
  },
  {
    id: 'makan',
    word: 'Makan',
    pronunciation: 'mah-kahn',
    phonetic: '/ˈmɑːkɑːn/',
    meaning: "To eat, or food itself — Malay in origin, and one of the most-used words in everyday Singapore English regardless of who's speaking.",
    category: 'lingo',
    difficulty: 1,
    usedIn: ['Friends', 'Colleagues', 'Nearly any conversation about food or meals'],
    examples: [
      { text: 'Eh, makan already or not?' },
      { text: "Let's go makan, I'm starving." },
    ],
    missionId: 'speak',
  },
  {
    id: 'siao',
    word: 'Siao',
    pronunciation: 'see-ow',
    phonetic: '/ˈsiːaʊ/',
    meaning: "Crazy — for genuinely reckless behaviour, or (much more often) light-hearted disbelief at something wild.",
    category: 'lingo',
    difficulty: 2,
    usedIn: ['Friends', 'Reacting to something wild or over-the-top'],
    notUsedIn: ['Talking about actual mental health — this is casual slang, not clinical'],
    examples: [
      { text: 'You queued 3 hours for bubble tea? Siao!' },
      { text: 'Wah you siao ah, that\'s way too spicy for me.' },
    ],
    missionId: 'speak',
  },

  // Eat Like a Local
  {
    id: 'hawker-centre',
    word: 'Hawker Centre',
    pronunciation: 'haw-ker sen-ter',
    phonetic: '/ˈhɔːkə ˈsɛntə/',
    meaning: 'An open-air complex of food stalls run by individual hawkers — Singapore\'s everyday dining default.',
    category: 'food',
    difficulty: 1,
    usedIn: ['Everyday conversation about where to eat'],
    examples: [
      { text: "Let's go the hawker centre for lunch." },
    ],
    missionId: 'eat',
  },
  {
    id: 'die-die-must-try',
    word: 'Die Die Must Try',
    pronunciation: 'die die must try',
    phonetic: '/daɪ daɪ mʌst traɪ/',
    meaning: 'The strongest possible food recommendation — something so good it\'s non-negotiable.',
    category: 'food',
    difficulty: 1,
    usedIn: ['Friends', 'Food recommendations of any kind'],
    examples: [
      { text: 'This chicken rice stall — die die must try.' },
    ],
    missionId: 'eat',
  },
  {
    id: 'chope',
    word: 'Chope',
    pronunciation: 'chope (rhymes with "hope")',
    phonetic: '/tʃoʊp/',
    meaning: "To reserve a seat or table, usually by leaving a small item like a packet of tissues on it.",
    category: 'food',
    difficulty: 1,
    usedIn: ['Friends', 'Colleagues', 'Hawker centres and food courts'],
    notUsedIn: ['Formal reservations — this is an informal, unofficial system'],
    commonMistakes: [
      "Don't assume a bag/tissue packet on a seat means it's free — it almost always means the opposite.",
    ],
    examples: [
      { text: "I'll chope a table, you go queue for drinks." },
      { text: "Eh, that seat's choped already — tissue packet there." },
    ],
    missionId: 'eat',
  },
  {
    id: 'kopi',
    word: 'Kopi',
    pronunciation: 'koh-pee',
    phonetic: '/ˈkoʊpi/',
    meaning: 'Coffee with condensed milk — the default coffee order at a kopitiam (coffee shop).',
    category: 'food',
    difficulty: 1,
    usedIn: ['Ordering at a kopitiam or hawker drink stall'],
    examples: [
      { text: 'One kopi, less sweet, thanks.' },
    ],
    missionId: 'eat',
  },
  {
    id: 'kopi-peng',
    word: 'Kopi Peng',
    pronunciation: 'koh-pee peng',
    phonetic: '/ˈkoʊpi pɛŋ/',
    meaning: "Iced version of kopi — 'peng' means ice, and it modifies almost any drink order the same way.",
    category: 'food',
    difficulty: 2,
    usedIn: ['Ordering at a kopitiam or hawker drink stall'],
    commonMistakes: [
      "Don't forget 'peng' only means iced — the milk/sugar code (O, C, kosong) still applies on top of it.",
    ],
    examples: [
      { text: 'Kopi peng for me, so hot today.' },
      { text: 'Teh peng also can.' },
    ],
    missionId: 'eat',
  },
  {
    id: 'teh-tarik',
    word: 'Teh Tarik',
    pronunciation: 'teh tah-rik',
    phonetic: '/tɛ ˈtɑːrɪk/',
    meaning: '"Pulled tea" — milk tea theatrically poured back and forth between two cups to froth it up.',
    category: 'food',
    difficulty: 2,
    usedIn: ['Ordering at a kopitiam', 'Describing the drink itself'],
    examples: [
      { text: 'One teh tarik, extra frothy!' },
    ],
    missionId: 'eat',
  },
  {
    id: 'tray-return',
    word: 'Tray Return',
    pronunciation: 'tray ri-turn',
    phonetic: '/treɪ rɪˈtɜːn/',
    meaning: 'The point where you clear your own tray and dishes after eating at a hawker centre — expected, not optional.',
    category: 'food',
    difficulty: 1,
    usedIn: ['Any hawker centre or food court'],
    commonMistakes: [
      "Don't just walk off — leaving your tray is a genuine faux pas, and in many hawker centres it's legally required.",
    ],
    examples: [
      { text: "Let's return our trays before we go." },
    ],
    missionId: 'eat',
  },
  {
    id: 'dabao',
    word: 'Dabao',
    pronunciation: 'dah-bao',
    phonetic: '/dɑːˈbaʊ/',
    meaning: 'To take away or package food to go — also spelled tapau/tapao.',
    category: 'food',
    difficulty: 2,
    usedIn: ['Friends', 'Colleagues', 'Ordering at hawker stalls'],
    examples: [
      { text: 'Dabao the chicken rice for me, I need to rush back.' },
      { text: "Eating here or dabao?" },
    ],
    missionId: 'eat',
  },
  {
    id: 'sedap',
    word: 'Sedap',
    pronunciation: 'suh-dahp',
    phonetic: '/səˈdɑːp/',
    meaning: 'Delicious — a Malay word for good food, used constantly regardless of your own background.',
    category: 'food',
    difficulty: 1,
    usedIn: ['Complimenting food, any cuisine'],
    examples: [
      { text: 'This nasi lemak is so sedap.' },
    ],
    missionId: 'eat',
  },

  // Move Like a Local
  {
    id: 'mrt',
    word: 'MRT',
    pronunciation: 'em-ar-tee',
    phonetic: '/ˌɛm ɑːr ˈtiː/',
    meaning: "Mass Rapid Transit — Singapore's subway/metro system, the backbone of getting around.",
    category: 'gettingAround',
    difficulty: 1,
    usedIn: ['Everyday conversation about commuting'],
    examples: [
      { text: "I'll take the MRT, faster than driving." },
    ],
    missionId: 'move',
  },
  {
    id: 'tap-in-tap-out',
    word: 'Tap In, Tap Out',
    pronunciation: 'tap in, tap out',
    phonetic: '/tæp ɪn tæp aʊt/',
    meaning: 'The fare system: tap your card/phone at the gantry entering and leaving the MRT or bus.',
    category: 'gettingAround',
    difficulty: 1,
    usedIn: ['Every MRT and bus ride'],
    commonMistakes: [
      "Don't forget to tap out — skipping it can trigger a maximum fare charge or flag your card.",
    ],
    examples: [
      { text: 'Just tap in with your phone, no need to buy a ticket.' },
    ],
    missionId: 'move',
  },
  {
    id: 'stand-left',
    word: 'Stand Left, Walk Right',
    pronunciation: 'stand left, walk right',
    phonetic: '/stænd lɛft wɔːk raɪt/',
    meaning: 'The near-universal escalator norm: stand on the left, leave the right lane clear for people walking up.',
    category: 'gettingAround',
    difficulty: 1,
    usedIn: ['Every escalator, especially in MRT stations'],
    examples: [
      { text: 'Stand left ah, got people rushing behind.' },
    ],
    missionId: 'move',
  },
  {
    id: 'alight',
    word: 'Alight',
    pronunciation: 'uh-lite',
    phonetic: '/əˈlaɪt/',
    meaning: 'To get off a bus or train — standard Singapore English on transit announcements, less common elsewhere.',
    category: 'gettingAround',
    difficulty: 1,
    usedIn: ['Bus/MRT announcements', 'Everyday transit conversation'],
    examples: [
      { text: 'Please press the bell before you alight.' },
      { text: 'Which stop are you alighting at?' },
    ],
    missionId: 'move',
  },
  {
    id: 'grab',
    word: 'Grab',
    pronunciation: 'grab',
    phonetic: '/ɡræb/',
    meaning: "Singapore's dominant ride-hailing app — used as both the app name and a verb.",
    category: 'gettingAround',
    difficulty: 1,
    usedIn: ['Everyday conversation about getting somewhere'],
    examples: [
      { text: "It's late, let's just Grab home." },
    ],
    missionId: 'move',
  },
  {
    id: 'which-exit',
    word: 'Which Exit',
    pronunciation: 'wich eks-it',
    phonetic: '/wɪtʃ ˈɛksɪt/',
    meaning: 'The go-to wayfinding question at MRT stations, which often have many numbered/lettered exits far apart.',
    category: 'gettingAround',
    difficulty: 1,
    usedIn: ['Asking directions', 'Coordinating a meetup point'],
    examples: [
      { text: 'Which exit ah? This station got like six.' },
    ],
    missionId: 'move',
  },
  {
    id: 'peak-hour',
    word: 'Peak Hour',
    pronunciation: 'peek our',
    phonetic: '/piːk ˈaʊə/',
    meaning: "Rush hour — when trains and buses are most crowded, roughly weekday mornings and evenings.",
    category: 'gettingAround',
    difficulty: 1,
    usedIn: ['Planning a commute', 'Everyday conversation'],
    examples: [
      { text: "Avoid peak hour if you can, train is packed." },
    ],
    missionId: 'move',
  },

  // Vibe Like a Local
  {
    id: 'queue',
    word: 'Queue',
    pronunciation: 'kyoo',
    phonetic: '/kjuː/',
    meaning: 'A line — queueing is taken seriously here, even without ropes or signage marking it.',
    category: 'socialVibes',
    difficulty: 1,
    usedIn: ['Everywhere — hawker stalls, buses, lifts, shops'],
    commonMistakes: [
      "Don't assume no visible queue means no queue — a quick 'is this the line?' avoids accidentally cutting in.",
    ],
    examples: [
      { text: 'Is this the queue for chicken rice?' },
    ],
    missionId: 'vibe',
  },
  {
    id: 'not-bad',
    word: 'Not Bad',
    pronunciation: 'not bad',
    phonetic: '/nɒt bæd/',
    meaning: "A classic understatement — said low-key, it genuinely means 'good', not lukewarm.",
    category: 'socialVibes',
    difficulty: 2,
    usedIn: ['Friends', 'Colleagues', 'Everyday feedback'],
    commonMistakes: [
      "Don't read disappointment into it — 'can lah, not bad' is closer to praise than complaint.",
    ],
    examples: [
      { text: '"How was the food?" — "Can lah, not bad."' },
    ],
    missionId: 'vibe',
  },
  {
    id: 'auntie-uncle',
    word: 'Auntie / Uncle',
    pronunciation: 'ahn-tee / uhng-kuhl',
    phonetic: '/ˈɑːnti/ /ˈʌŋkəl/',
    meaning: 'A warm, respectful way to address an older stranger — a hawker stall owner, a cleaner, anyone noticeably older than you.',
    category: 'socialVibes',
    difficulty: 1,
    usedIn: ['Addressing hawker stall owners', 'Addressing elders you don\'t know'],
    notUsedIn: ["Peers your own age — it's specifically for people clearly older"],
    examples: [
      { text: 'Auntie, one kopi peng please!' },
      { text: 'Uncle, how much ah?' },
    ],
    missionId: 'vibe',
  },
  {
    id: 'kaypoh',
    word: 'Kaypoh',
    pronunciation: 'kay-poh',
    phonetic: '/ˈkeɪpoʊ/',
    meaning: 'A busybody — nosy, overly curious about other people\'s business.',
    category: 'socialVibes',
    difficulty: 2,
    usedIn: ['Friends', 'Light teasing about someone prying'],
    notUsedIn: ['As a harsh accusation — usually said half-jokingly'],
    examples: [
      { text: "Don't be so kaypoh, it's none of our business." },
    ],
    missionId: 'vibe',
  },
  {
    id: 'wah',
    word: 'Wah',
    pronunciation: 'wah',
    phonetic: '/wɑː/',
    meaning: 'An exclamation of surprise, enthusiasm, or admiration — like "wow" but used constantly.',
    category: 'socialVibes',
    difficulty: 1,
    usedIn: ['Friends', 'Colleagues', 'Almost any reaction'],
    examples: [
      { text: 'Wah, sounds good, where you thinking?' },
      { text: 'Wah, that queue so long.' },
    ],
    missionId: 'vibe',
  },
  {
    id: 'bo-jio',
    word: 'Bo Jio',
    pronunciation: 'boh jee-oh',
    phonetic: '/boʊ dʒiːoʊ/',
    meaning: '"You didn\'t invite me!" — a playful complaint about being left out of plans, Hokkien origin.',
    category: 'socialVibes',
    difficulty: 2,
    usedIn: ['Friends', 'Colleagues', 'Reacting to plans you weren\'t included in'],
    examples: [
      { text: 'You guys went for makan without me? Bo jio!' },
    ],
    missionId: 'vibe',
  },
  {
    id: 'lepak',
    word: 'Lepak',
    pronunciation: 'leh-pahk',
    phonetic: '/ˈlɛpɑːk/',
    meaning: 'To chill, hang out, or relax with no particular agenda — Malay origin.',
    category: 'socialVibes',
    difficulty: 1,
    usedIn: ['Friends', 'Casual weekend plans'],
    examples: [
      { text: 'No plans this weekend, just gonna lepak at home.' },
      { text: 'Wanna lepak at the void deck later?' },
    ],
    missionId: 'vibe',
  },

  // Work Like a Local
  {
    id: 'on-the-dot',
    word: 'On The Dot',
    pronunciation: 'on thuh dot',
    phonetic: '/ɒn ðə dɒt/',
    meaning: 'Exactly on time — used to stress that punctuality is expected, not a rough guideline.',
    category: 'workCulture',
    difficulty: 1,
    usedIn: ['Meetings', 'Work commitments'],
    examples: [
      { text: 'Meeting starts 9am on the dot, don\'t be late.' },
    ],
    missionId: 'work',
  },
  {
    id: 'noted',
    word: 'Noted',
    pronunciation: 'noh-tid',
    phonetic: '/ˈnoʊtɪd/',
    meaning: 'A short, common work-chat acknowledgment — confirms you\'ve seen and understood a message.',
    category: 'workCulture',
    difficulty: 1,
    usedIn: ['Work chats', 'Emails'],
    notUsedIn: ['Situations needing more than a bare acknowledgment — pair it with a next step if one\'s expected'],
    examples: [
      { text: 'Noted, will send the deck by 3pm.' },
    ],
    missionId: 'work',
  },
  {
    id: 'arrow',
    word: 'Arrow',
    pronunciation: 'a-roh',
    phonetic: '/ˈæroʊ/',
    meaning: 'To dump an unwanted task onto someone else — used as a verb, often about being on the receiving end.',
    category: 'workCulture',
    difficulty: 2,
    usedIn: ['Colleagues', 'Complaining about workload, lightheartedly or not'],
    examples: [
      { text: 'I got arrowed to run the year-end event again.' },
      { text: "Don't arrow it to the new intern lah." },
    ],
    missionId: 'work',
  },
  {
    id: 'jio',
    word: 'Jio',
    pronunciation: 'jee-oh',
    phonetic: '/dʒiːoʊ/',
    meaning: 'To invite someone along to something — casual and warm.',
    category: 'workCulture',
    difficulty: 2,
    usedIn: ['Colleagues', 'Friends', 'Casual invitations'],
    examples: [
      { text: 'Jio you for lunch later, hawker centre okay?' },
      { text: 'Next time jio me also ah!' },
    ],
    missionId: 'work',
  },
  {
    id: 'zai',
    word: 'Zai',
    pronunciation: 'zye',
    phonetic: '/zaɪ/',
    meaning: 'Skilled, sharp, on top of things — genuine praise for someone good at their job.',
    category: 'workCulture',
    difficulty: 2,
    usedIn: ['Colleagues', 'Complimenting competence'],
    examples: [
      { text: "She's so zai, closed the deal in one meeting." },
    ],
    missionId: 'work',
  },
];
